MI5-58 Feature/UI filtriranje transakcija
air2024-mi5/sustav-za-obradu-karticnih-platnih-transakcija-android pull request #19
Opened 2024-12-21 23:42 UTC by bkadezabe20

Dodani je UI za filtriranje transakcija. Filtriranje se radi preko ModalBottomSheetFilter-a.

Filtriranje se za sada radi nad Datumom, Min Max, vrstama kartica i vrstama transakcija.

Filteri se lako mogu maknuti i promjeniti trenutno postavljeni filter

2024-12-22 16:37 UTC, NinoLoncar requested changes

2024-12-22 16:37 UTC, NinoLoncar commented on app/src/main/java/foi/air/szokpt/views/app/TransactionsView.kt
> +)
Ovo je potrebno izdvojiti u zasebnu datoteku. Možda bi bolji naziv bio TransactionFilter.

2024-12-22 16:37 UTC, NinoLoncar commented on app/src/main/java/foi/air/szokpt/views/app/TransactionsView.kt
> +}
Izdvojiti u zasebnu datoteku.

2024-12-22 16:37 UTC, NinoLoncar commented on app/src/main/java/foi/air/szokpt/views/app/TransactionsView.kt
>  }
Izdvojiti u zasebnu datoteku.

2025-01-03 18:36 UTC, bkadezabe20 commented on app/src/main/java/foi/air/szokpt/views/app/TransactionsView.kt
> +)
Po f9669d2

2025-01-03 18:37 UTC, bkadezabe20 commented on app/src/main/java/foi/air/szokpt/views/app/TransactionsView.kt
> +}
Riješeno po f9669d2

2025-01-03 18:37 UTC, bkadezabe20 commented on app/src/main/java/foi/air/szokpt/views/app/TransactionsView.kt
>  }
Riješeno po f9669d2

2025-01-06 12:44 UTC, NinoLoncar approved these changes
Sada izgleda puno bolje

2025-01-06 14:26 UTC, phajdarov21 approved these changes
Sve izgleda dobro.

2025-01-06 20:14 UTC, merged